'use strict';
const API='https://pokeapi.co/api/v2'; const MAX=1025;
const REGIONS=[['Kanto',1,151],['Johto',152,251],['Hoenn',252,386],['Sinnoh',387,493],['Unova',494,649],['Kalos',650,721],['Alola',722,809],['Galar',810,898],['Hisui',899,905],['Paldea',906,1025]];
const UB=new Set([793,794,795,796,797,798,799,803,804,805,806]);
const STARTERS=new Set([1,2,3,4,5,6,7,8,9,152,153,154,155,156,157,158,159,160,252,253,254,255,256,257,258,259,260,387,388,389,390,391,392,393,394,395,495,496,497,498,499,500,501,502,503,650,651,652,653,654,655,656,657,658,722,723,724,725,726,727,728,729,730,810,811,812,813,814,815,816,817,818,906,907,908,909,910,911,912,913,914]);
// Species with a known Mega Evolution as of Sep 2026, including Legends: Z-A + Mega Dimension.
const MEGA=new Set([3,6,9,15,18,26,36,65,71,80,94,115,121,127,130,142,150,154,160,181,208,212,214,229,248,254,257,260,282,302,303,306,308,310,319,323,334,354,359,362,373,376,380,381,384,428,445,448,460,475,531,719,9,18,26,36,71,121,149,154,160,227,358,359,398,445,448,478,485,491,500,530,545,560,604,609,623,652,655,658,668,670,678,687,689,691,701,718,740,768,780,801,807,870,952,970,978,998]);
const GMAX=new Set([3,6,9,12,25,52,68,94,99,131,133,143,569,809,812,815,818,823,826,834,839,841,842,844,849,851,858,861,869,879,884,892]);
const state={list:[],details:new Map(),species:new Map(),activeCategory:'all',activeRegion:'all',activeTeam:null,rouletteVisible:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem('pt_'+k))??d}catch{return d}},set(k,v){try{localStorage.setItem('pt_'+k,JSON.stringify(v))}catch{}}};
let favs=new Set(store.get('favs',[])), teams=store.get('teams',[]), roulette=new Set(store.get('roulette',[])), recent=store.get('recent',[]);
const cap=s=>s? s.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase()):''; const pad=n=>String(n).padStart(4,'0');
function regionOf(id){return REGIONS.find(r=>id>=r[1]&&id<=r[2])?.[0]||'—'}
function sprite(id,shiny=false){return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${shiny?'shiny/':''}${id}.png`}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function safe(fn){try{return fn()}catch(e){console.error(e);toast('Algo deu errado, mas o restante do site continua funcionando.')}}
function save(){store.set('favs',[...favs]);store.set('teams',teams);store.set('roulette',[...roulette]);store.set('recent',recent);updateHome()}
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='wishes')renderFavs();if(page==='teams')renderTeams();if(page==='roulette'){renderPicker();drawWheel()}if(page==='home')updateHome()}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
function setupSelects(){const opts='<option value="all">Todas as regiões</option>'+REGIONS.map(r=>`<option value="${r[0]}">${r[0]} — #${r[1]}–#${r[2]}</option>`).join('');$('#regionFilter').innerHTML=opts;$('#rouletteRegion').innerHTML=opts;const cats=[['all','🔹 Todos'],['legendary','🟡 Lendários'],['mythical','🔵 Míticos'],['ub','🟣 Ultra Beasts'],['starter','🌱 Iniciais Regionais'],['mega','💥 Mega Evoluções'],['gmax','⚡ Gigantamax']];$('#categoryFilters').innerHTML=cats.map(([v,l])=>`<button data-cat="${v}" class="${v==='all'?'active':''}">${l}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{state.activeCategory=b.dataset.cat;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderDex()})}
async function fetchJSON(url,key){const cached=store.get('cache_'+key,null);if(cached)return cached;const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw new Error(r.status);const j=await r.json();store.set('cache_'+key,j);return j}finally{clearTimeout(timer)}}
async function initData(){try{const data=await fetchJSON(`${API}/pokemon?limit=${MAX}&offset=0`,'list_v3');state.list=data.results.slice(0,MAX).map((p,i)=>({id:i+1,name:p.name}));$('#loadStatus').textContent=`${state.list.length} espécies carregadas • detalhes progressivos`;renderDex();renderPicker();progressiveDetails()}catch(e){console.error(e);state.list=Array.from({length:MAX},(_,i)=>({id:i+1,name:`pokemon-${i+1}`}));$('#dexMessage').classList.remove('hidden');$('#dexMessage').textContent='Não foi possível carregar os nomes da PokéAPI. A navegação continua disponível; verifique sua conexão e tente recarregar.';$('#loadStatus').textContent='PokéAPI indisponível';renderDex()}}
async function getDetail(id){if(state.details.has(id))return state.details.get(id);try{const p=await fetchJSON(`${API}/pokemon/${id}`,'pokemon_'+id);const d={id,name:p.name,types:p.types.sort((a,b)=>a.slot-b.slot).map(x=>x.type.name),forms:p.forms?.map(x=>x.name)||[]};state.details.set(id,d);return d}catch(e){console.warn('detail failed',id,e);return {id,name:state.list[id-1]?.name||`#${id}`,types:[],forms:[]}}}
async function getSpecies(id){if(state.species.has(id))return state.species.get(id);try{const s=await fetchJSON(`${API}/pokemon-species/${id}`,'species_'+id);state.species.set(id,s);return s}catch(e){console.warn('species failed',id,e);return null}}
async function progressiveDetails(){let next=1,workers=10;async function worker(){while(next<=MAX){const id=next++;await getDetail(id);if(id%25===0&&$('#pokedex').classList.contains('active'))renderDex();}}await Promise.allSettled(Array.from({length:workers},worker));$('#loadStatus').textContent='Pokédex pronta • dados em cache';renderDex();renderPicker()}
function matchesSearch(p,q){if(!q)return true;q=q.trim().toLowerCase();const n=parseInt(q,10);return p.name.toLowerCase().includes(q)||(!Number.isNaN(n)&&p.id===n)}
async function ensureCategoryFlags(ids){if(!['legendary','mythical'].includes(state.activeCategory))return;const missing=ids.filter(id=>!state.species.has(id));let i=0;async function w(){while(i<missing.length){await getSpecies(missing[i++])}}await Promise.allSettled(Array.from({length:8},w))}
function categoryMatch(p){if(state.activeCategory==='all')return true;if(state.activeCategory==='ub')return UB.has(p.id);if(state.activeCategory==='starter')return STARTERS.has(p.id);if(state.activeCategory==='mega')return MEGA.has(p.id);if(state.activeCategory==='gmax')return GMAX.has(p.id);const s=state.species.get(p.id);if(state.activeCategory==='legendary')return !!s?.is_legendary;if(state.activeCategory==='mythical')return !!s?.is_mythical;return true}
let dexToken=0;async function renderDex(){const token=++dexToken,q=$('#dexSearch').value;let base=state.list.filter(p=>matchesSearch(p,q)&& (state.activeRegion==='all'||regionOf(p.id)===state.activeRegion));if(['legendary','mythical'].includes(state.activeCategory)){$('#dexResults').innerHTML='<div class="empty-state">Conferindo classificação oficial na PokéAPI…</div>';await ensureCategoryFlags(base.map(p=>p.id));if(token!==dexToken)return}const list=base.filter(categoryMatch).sort((a,b)=>a.id-b.id);$('#dexResults').innerHTML=list.length?REGIONS.map(r=>{const arr=list.filter(p=>regionOf(p.id)===r[0]);return arr.length?`<section class="region-section"><div class="region-title"><h2>${r[0]}</h2><span>${arr.length} Pokémon</span></div><div class="card-grid">${arr.map(cardHTML).join('')}</div></section>`:''}).join(''):'<div class="empty-state">Nenhum Pokémon encontrado.</div>';bindCards($('#dexResults'))}
function cardHTML(p){const d=state.details.get(p.id),types=d?.types||[];return `<article class="poke-card" data-id="${p.id}"><div class="card-actions"><button class="fav ${favs.has(p.id)?'on':''}" data-fav="${p.id}" aria-label="Favoritar">★</button><button data-add="${p.id}" aria-label="Adicionar ao time">＋</button></div><span class="num">#${pad(p.id)}</span><img loading="lazy" src="${sprite(p.id)}" onerror="this.style.opacity=.2" alt="${cap(p.name)}"><h3>${cap(p.name)}</h3><div class="types">${types.length?types.map(t=>`<span class="type ${t}">${t}</span>`).join(''):'<span class="muted">carregando tipos…</span>'}</div></article>`}
function bindCards(root){root.querySelectorAll('.poke-card').forEach(c=>c.onclick=e=>{if(e.target.closest('button'))return;openPokemon(+c.dataset.id)});root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(+b.dataset.fav);b.classList.toggle('on',favs.has(+b.dataset.fav))});root.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addToTeam(+b.dataset.add)})}
function toggleFav(id){favs.has(id)?favs.delete(id):favs.add(id);save();toast(favs.has(id)?'Adicionado aos desejos ⭐':'Removido dos desejos')}
async function openPokemon(id){const d=await getDetail(id),s=await getSpecies(id);recent=[id,...recent.filter(x=>x!==id)].slice(0,8);save();let evo='<span class="muted">Evolução indisponível.</span>';if(s?.evolution_chain?.url){try{const chain=await fetchJSON(s.evolution_chain.url,'evo_'+s.evolution_chain.url.split('/').filter(Boolean).pop());const paths=[];function walk(node,path=[]){const nid=+(node.species.url.match(/\/(\d+)\/$/)||[])[1];const np=[...path,{id:nid,name:node.species.name}];if(!node.evolves_to.length)paths.push(np);else node.evolves_to.forEach(n=>walk(n,np))}walk(chain.chain);evo=paths.map(path=>`<div class="evo">${path.map((x,i)=>`${i?'→':''}<button data-evo="${x.id}"><img loading="lazy" src="${sprite(x.id)}">${cap(x.name)}</button>`).join('')}</div>`).join('')}catch(e){console.warn(e)}}const forms=d.forms?.map(cap).join(', ')||'Forma padrão';$('#modalContent').innerHTML=`<div class="detail-top"><img id="detailImg" src="${sprite(id)}"><div><span class="num">#${pad(id)} • ${regionOf(id)}</span><h2>${cap(d.name)}</h2><div class="types">${d.types.map(t=>`<span class="type ${t}">${t}</span>`).join('')}</div><p class="muted">Formas registradas: ${forms}</p><div class="detail-actions"><button id="shinyBtn">✨ Shiny: OFF</button><button id="modalFav" class="fav ${favs.has(id)?'on':''}">★ Favoritar</button><button id="modalAdd" class="primary">＋ Adicionar ao time</button></div></div></div><h3>Linha Evolutiva</h3>${evo}`;$('#modal').classList.remove('hidden');let shiny=false;$('#shinyBtn').onclick=()=>{shiny=!shiny;$('#detailImg').src=sprite(id,shiny);$('#shinyBtn').textContent=`✨ Shiny: ${shiny?'ON':'OFF'}`};$('#modalFav').onclick=()=>{toggleFav(id);$('#modalFav').classList.toggle('on',favs.has(id))};$('#modalAdd').onclick=()=>addToTeam(id);$$('[data-evo]').forEach(b=>b.onclick=()=>openPokemon(+b.dataset.evo))}
$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
function updateHome(){ $('#homeFavs').textContent=favs.size;$('#homeTeams').textContent=teams.length;$('#homeRoulette').textContent=roulette.size;const box=$('#recentList');if(!recent.length){box.className='mini-list empty-state';box.textContent='Nenhum Pokémon pesquisado ainda.';return}box.className='mini-list';box.innerHTML=recent.map(id=>{const p=state.list[id-1]||{name:`#${id}`};return `<button class="mini-poke" data-recent="${id}"><img src="${sprite(id)}">${cap(p.name)}</button>`}).join('');$$('[data-recent]').forEach(b=>b.onclick=()=>openPokemon(+b.dataset.recent))}
function renderFavs(){const q=$('#favSearch').value.toLowerCase();const arr=[...favs].sort((a,b)=>a-b).map(id=>state.list[id-1]||{id,name:`pokemon-${id}`}).filter(p=>matchesSearch(p,q));$('#favResults').innerHTML=arr.length?arr.map(cardHTML).join(''):'<div class="empty-state">Sua lista de desejos está vazia.</div>';bindCards($('#favResults'))}
$('#clearFavs').onclick=()=>{if(favs.size&&confirm('Remover todos os favoritos?')){favs.clear();save();renderFavs()}};$('#favSearch').oninput=renderFavs;
function createTeam(){const name=prompt('Nome da nova equipe:','Equipe '+(teams.length+1));if(!name)return;const id=Date.now();teams.push({id,name:name.trim().slice(0,40),members:[]});state.activeTeam=id;save();renderTeams()}
function renderTeams(){if(!teams.length){$('#teamTabs').innerHTML='';$('#teamArea').innerHTML='<div class="panel empty-state">Você ainda não criou equipes. Clique em “+ Criar equipe”.</div>';return}if(!teams.some(t=>t.id===state.activeTeam))state.activeTeam=teams[0].id;$('#teamTabs').innerHTML=teams.map(t=>`<button data-team="${t.id}" class="${t.id===state.activeTeam?'active':''}">${t.name}</button>`).join('');$$('[data-team]').forEach(b=>b.onclick=()=>{state.activeTeam=+b.dataset.team;renderTeams()});const t=teams.find(x=>x.id===state.activeTeam);const slots=Array.from({length:6},(_,i)=>{const id=t.members[i];if(!id)return '<div class="slot">Espaço vazio</div>';const p=state.list[id-1]||{name:`#${id}`},d=state.details.get(id);return `<div class="slot filled"><img src="${sprite(id)}"><h4>${cap(p.name)}</h4><small>#${pad(id)} ${d?.types?.join(' / ')||''}</small><button data-remove-member="${i}">Remover</button></div>`}).join('');$('#teamArea').innerHTML=`<div class="team-card"><div class="team-head"><h2>${t.name}</h2><div><button id="renameTeam">Renomear</button> <button id="clearTeam">Limpar</button> <button id="deleteTeam" class="danger">Excluir</button></div></div><div class="team-slots">${slots}</div></div>`;$$('[data-remove-member]').forEach(b=>b.onclick=()=>{t.members.splice(+b.dataset.removeMember,1);save();renderTeams()});$('#renameTeam').onclick=()=>{const n=prompt('Novo nome:',t.name);if(n){t.name=n.trim().slice(0,40);save();renderTeams()}};$('#clearTeam').onclick=()=>{if(confirm('Limpar esta equipe?')){t.members=[];save();renderTeams()}};$('#deleteTeam').onclick=()=>{if(confirm('Excluir esta equipe?')){teams=teams.filter(x=>x.id!==t.id);state.activeTeam=teams[0]?.id||null;save();renderTeams()}}}
function addToTeam(id){if(!teams.length){toast('Crie uma equipe primeiro ⚔️');go('teams');return}const t=teams.find(x=>x.id===state.activeTeam)||teams[0];if(t.members.length>=6){toast(`${t.name} já tem 6 Pokémon.`);return}t.members.push(id);save();toast(`${cap(state.list[id-1]?.name||'Pokémon')} adicionado a ${t.name}`)}
$('#newTeam').onclick=createTeam;
function rouletteFiltered(){const q=$('#rouletteSearch').value,reg=$('#rouletteRegion').value;return state.list.filter(p=>matchesSearch(p,q)&&(reg==='all'||regionOf(p.id)===reg))}
function renderPicker(){const arr=rouletteFiltered();state.rouletteVisible=arr.map(x=>x.id);$('#rouletteCount').textContent=`${roulette.size} selecionados`;$('#probabilityText').textContent=roulette.size?`Cada Pokémon tem exatamente ${(100/roulette.size).toFixed(6).replace(/0+$/,'').replace(/\.$/,'')}% de chance (1/${roulette.size}).`:'Selecione Pokémon para começar.';$('#roulettePicker').innerHTML=arr.map(p=>`<div class="picker-row"><label><input type="checkbox" data-pick="${p.id}" ${roulette.has(p.id)?'checked':''}><img loading="lazy" src="${sprite(p.id)}"><span><b>#${pad(p.id)}</b> ${cap(p.name)}<br><small class="muted">${regionOf(p.id)}</small></span></label></div>`).join('');$$('[data-pick]').forEach(c=>c.onchange=()=>{c.checked?roulette.add(+c.dataset.pick):roulette.delete(+c.dataset.pick);save();$('#rouletteCount').textContent=`${roulette.size} selecionados`;drawWheel();renderProbability()})}
function renderProbability(){$('#probabilityText').textContent=roulette.size?`Cada Pokémon tem exatamente ${(100/roulette.size).toFixed(6).replace(/0+$/,'').replace(/\.$/,'')}% de chance (1/${roulette.size}).`:'Selecione Pokémon para começar.'}
function drawWheel(){const canvas=$('#wheel'),ctx=canvas.getContext('2d'),ids=[...roulette],n=ids.length,w=canvas.width,c=w/2,r=c-10;ctx.clearRect(0,0,w,w);if(!n){ctx.fillStyle='#172033';ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9aa7bd';ctx.font='700 22px system-ui';ctx.textAlign='center';ctx.fillText('Selecione Pokémon',c,c);return}const visual=ids.length>60?ids.slice(0,60):ids;const vn=visual.length;for(let i=0;i<vn;i++){const a0=-Math.PI/2+i*2*Math.PI/vn,a1=-Math.PI/2+(i+1)*2*Math.PI/vn;ctx.beginPath();ctx.moveTo(c,c);ctx.arc(c,c,r,a0,a1);ctx.closePath();ctx.fillStyle=`hsl(${(i*360/vn)%360} 62% 48%)`;ctx.fill();ctx.strokeStyle='#0b1020';ctx.stroke();if(vn<=24){ctx.save();ctx.translate(c,c);ctx.rotate((a0+a1)/2);ctx.textAlign='right';ctx.fillStyle='white';ctx.font='700 14px system-ui';ctx.fillText(cap(state.list[visual[i]-1]?.name||visual[i]),r-18,5);ctx.restore()}}ctx.beginPath();ctx.arc(c,c,42,0,Math.PI*2);ctx.fillStyle='#f5f7fb';ctx.fill();ctx.strokeStyle='#0b1020';ctx.lineWidth=10;ctx.stroke();if(ids.length>60){ctx.fillStyle='#101624';ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.fillText(`${ids.length} opções`,c,c+5)}}
let spinning=false,rotation=0;$('#spin').onclick=()=>{if(spinning)return;if(!roulette.size){toast('Selecione pelo menos 1 Pokémon.');return}spinning=true;const ids=[...roulette];const idx=Math.floor(Math.random()*ids.length),winner=ids[idx];const n=ids.length;let target;if(n<=60){const slice=360/n;target=360-(idx*slice+slice/2)}else target=Math.random()*360;rotation+=360*7+target;$('#wheel').style.transform=`rotate(${rotation}deg)`;$('#spinResult').innerHTML='<div class="result-box">🎡 Girando…</div>';setTimeout(()=>{spinning=false;const p=state.list[winner-1]||{name:`#${winner}`};$('#spinResult').innerHTML=`<div class="result-box"><b>🎉 RESULTADO</b><br><img src="${sprite(winner)}"><h2>${cap(p.name)}</h2><p>#${pad(winner)} • ${regionOf(winner)}<br>Chance: ${(100/n).toFixed(8).replace(/0+$/,'').replace(/\.$/,'')}% (1/${n})</p></div>`},4600)};
$('#rouletteSearch').oninput=renderPicker;$('#rouletteRegion').onchange=renderPicker;$('#selectVisible').onclick=()=>{state.rouletteVisible.forEach(id=>roulette.add(id));save();renderPicker();drawWheel()};$('#removeVisible').onclick=()=>{state.rouletteVisible.forEach(id=>roulette.delete(id));save();renderPicker();drawWheel()};$('#clearRoulette').onclick=()=>{roulette.clear();save();renderPicker();drawWheel();$('#spinResult').innerHTML=''};
let debounce;$('#dexSearch').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(renderDex,120)};$('#regionFilter').onchange=e=>{state.activeRegion=e.target.value;$('#pokedex').animate?.([{opacity:.5},{opacity:1}],{duration:220});renderDex()};
window.addEventListener('error',e=>console.error('Non-fatal UI error:',e.error||e.message));window.addEventListener('unhandledrejection',e=>{console.error('Non-fatal promise error:',e.reason);e.preventDefault()});
setupSelects();updateHome();renderTeams();drawWheel();initData();
